version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    env_file: ../.env
    networks:
      - default
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "0.0.0.0:8001:80"
    env_file: ../.env
    volumes:
      - ./pgadmin4-servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - default
    links:
      - postgres:postgres

volumes:
  postgresdb:

networks:
  default:
    name: nextjs-chat-app-network